[package]
name = "parallel_indexed_reduce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
timeit = "*"
rand = "*"
parking_lot = "*"
rayon = "*"
smallvec = "*"