[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Need a crate to generate random numbers to compare against
# Let's do a search on https://crates.io
rand = "0.8"
